# Form implementation generated from reading ui file 'erreur.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os


class Ui_MessageDialog(QtWidgets.QDialog):
    def __init__(self, type, message):
        super().__init__()

        self.type = type

        self.setObjectName("MessageDialog")
        self.resize(400, 100)
        self.setWindowIcon(QtGui.QIcon(os.path.join(os.path.dirname(__file__), "ressources", "icon.png")))

        self.label = QtWidgets.QLabel(parent=self)
        self.label.setGeometry(QtCore.QRect(10, 5, 380, 60))
        self.label.setText(message)
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self)
        self.pushButton.setGeometry(QtCore.QRect(150, 70, 100, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.mousePressEvent = lambda event: self.destroy()

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MessageDialog", self.type))
        self.pushButton.setText(_translate("MessageDialog", "Continuer"))
